// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Twichirp.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Twichirp.Core.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SplashAccountLoading {
            get {
                return ResourceManager.GetString("SplashAccountLoading", resourceCulture);
            }
        }
        
        public static string SplashConsumerLoading {
            get {
                return ResourceManager.GetString("SplashConsumerLoading", resourceCulture);
            }
        }
        
        public static string SplashAccountDownLoading {
            get {
                return ResourceManager.GetString("SplashAccountDownLoading", resourceCulture);
            }
        }
        
        public static string LoginLoginButton {
            get {
                return ResourceManager.GetString("LoginLoginButton", resourceCulture);
            }
        }
        
        public static string LoginPinCode {
            get {
                return ResourceManager.GetString("LoginPinCode", resourceCulture);
            }
        }
        
        public static string LoginAuthenticate {
            get {
                return ResourceManager.GetString("LoginAuthenticate", resourceCulture);
            }
        }
        
        public static string LoginDescription {
            get {
                return ResourceManager.GetString("LoginDescription", resourceCulture);
            }
        }
        
        public static string MainAddAccount {
            get {
                return ResourceManager.GetString("MainAddAccount", resourceCulture);
            }
        }
        
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        public static string SettingGeneral {
            get {
                return ResourceManager.GetString("SettingGeneral", resourceCulture);
            }
        }
        
        public static string SettingApplication {
            get {
                return ResourceManager.GetString("SettingApplication", resourceCulture);
            }
        }
        
        public static string SettingOther {
            get {
                return ResourceManager.GetString("SettingOther", resourceCulture);
            }
        }
        
        public static string SettingCleanUp {
            get {
                return ResourceManager.GetString("SettingCleanUp", resourceCulture);
            }
        }
        
        public static string SettingCleanUpSummary {
            get {
                return ResourceManager.GetString("SettingCleanUpSummary", resourceCulture);
            }
        }
        
        public static string SettingUseAccount {
            get {
                return ResourceManager.GetString("SettingUseAccount", resourceCulture);
            }
        }
        
        public static string SettingAccount {
            get {
                return ResourceManager.GetString("SettingAccount", resourceCulture);
            }
        }
        
        public static string SettingTimeline {
            get {
                return ResourceManager.GetString("SettingTimeline", resourceCulture);
            }
        }
        
        public static string SettingTimelineDownloadCount {
            get {
                return ResourceManager.GetString("SettingTimelineDownloadCount", resourceCulture);
            }
        }
        
        public static string SettingTimelineOwnedNumber {
            get {
                return ResourceManager.GetString("SettingTimelineOwnedNumber", resourceCulture);
            }
        }
        
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        public static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        public static string OpenSourceLicense {
            get {
                return ResourceManager.GetString("OpenSourceLicense", resourceCulture);
            }
        }
        
        public static string OpenSourceCopying {
            get {
                return ResourceManager.GetString("OpenSourceCopying", resourceCulture);
            }
        }
        
        public static string OpenSourceCopyingLesser {
            get {
                return ResourceManager.GetString("OpenSourceCopyingLesser", resourceCulture);
            }
        }
        
        public static string OpenSourceCode {
            get {
                return ResourceManager.GetString("OpenSourceCode", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string LoadingLoad {
            get {
                return ResourceManager.GetString("LoadingLoad", resourceCulture);
            }
        }
        
        public static string StatusRetweetingUser {
            get {
                return ResourceManager.GetString("StatusRetweetingUser", resourceCulture);
            }
        }
        
        public static string StatusReplyToUser {
            get {
                return ResourceManager.GetString("StatusReplyToUser", resourceCulture);
            }
        }
        
        public static string TimeSecoundAgo {
            get {
                return ResourceManager.GetString("TimeSecoundAgo", resourceCulture);
            }
        }
        
        public static string TimeSecoundsAgo {
            get {
                return ResourceManager.GetString("TimeSecoundsAgo", resourceCulture);
            }
        }
        
        public static string TimeMinuteAgo {
            get {
                return ResourceManager.GetString("TimeMinuteAgo", resourceCulture);
            }
        }
        
        public static string TimeMinutesAgo {
            get {
                return ResourceManager.GetString("TimeMinutesAgo", resourceCulture);
            }
        }
        
        public static string TimeHourAgo {
            get {
                return ResourceManager.GetString("TimeHourAgo", resourceCulture);
            }
        }
        
        public static string TimeHoursAgo {
            get {
                return ResourceManager.GetString("TimeHoursAgo", resourceCulture);
            }
        }
        
        public static string TimeDayAgo {
            get {
                return ResourceManager.GetString("TimeDayAgo", resourceCulture);
            }
        }
        
        public static string TimeDaysAgo {
            get {
                return ResourceManager.GetString("TimeDaysAgo", resourceCulture);
            }
        }
        
        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        public static string TabMention {
            get {
                return ResourceManager.GetString("TabMention", resourceCulture);
            }
        }
        
        public static string TabDM {
            get {
                return ResourceManager.GetString("TabDM", resourceCulture);
            }
        }
        
        public static string TabUser {
            get {
                return ResourceManager.GetString("TabUser", resourceCulture);
            }
        }
        
        public static string TabTweet {
            get {
                return ResourceManager.GetString("TabTweet", resourceCulture);
            }
        }
        
        public static string TabFavorite {
            get {
                return ResourceManager.GetString("TabFavorite", resourceCulture);
            }
        }
        
        public static string TabFollowing {
            get {
                return ResourceManager.GetString("TabFollowing", resourceCulture);
            }
        }
        
        public static string TabFollower {
            get {
                return ResourceManager.GetString("TabFollower", resourceCulture);
            }
        }
        
        public static string UserFollowedBy {
            get {
                return ResourceManager.GetString("UserFollowedBy", resourceCulture);
            }
        }
        
        public static string UserFollowingReceived {
            get {
                return ResourceManager.GetString("UserFollowingReceived", resourceCulture);
            }
        }
        
        public static string UserBlockedBy {
            get {
                return ResourceManager.GetString("UserBlockedBy", resourceCulture);
            }
        }
        
        public static string UserFollowing {
            get {
                return ResourceManager.GetString("UserFollowing", resourceCulture);
            }
        }
        
        public static string UserFollowingRequested {
            get {
                return ResourceManager.GetString("UserFollowingRequested", resourceCulture);
            }
        }
        
        public static string UserBlocking {
            get {
                return ResourceManager.GetString("UserBlocking", resourceCulture);
            }
        }
        
        public static string UserFollow {
            get {
                return ResourceManager.GetString("UserFollow", resourceCulture);
            }
        }
        
        public static string UserMuting {
            get {
                return ResourceManager.GetString("UserMuting", resourceCulture);
            }
        }
        
        public static string UserMarkedSpam {
            get {
                return ResourceManager.GetString("UserMarkedSpam", resourceCulture);
            }
        }
        
        public static string UserDoFollow {
            get {
                return ResourceManager.GetString("UserDoFollow", resourceCulture);
            }
        }
        
        public static string UserDoUnfollow {
            get {
                return ResourceManager.GetString("UserDoUnfollow", resourceCulture);
            }
        }
        
        public static string UserDoBlock {
            get {
                return ResourceManager.GetString("UserDoBlock", resourceCulture);
            }
        }
        
        public static string UserDoUnblock {
            get {
                return ResourceManager.GetString("UserDoUnblock", resourceCulture);
            }
        }
        
        public static string UserDoMute {
            get {
                return ResourceManager.GetString("UserDoMute", resourceCulture);
            }
        }
        
        public static string UserDoUnmute {
            get {
                return ResourceManager.GetString("UserDoUnmute", resourceCulture);
            }
        }
        
        public static string UserDoSpam {
            get {
                return ResourceManager.GetString("UserDoSpam", resourceCulture);
            }
        }
    }
}
