//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twichirp.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twichirp.Core.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load More に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadingLoad {
            get {
                return ResourceManager.GetString("LoadingLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authenticate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginAuthenticate {
            get {
                return ResourceManager.GetString("LoginAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must authenticate on Twitter Site to use this application.\nAfter, input PIN Code to below text field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginDescription {
            get {
                return ResourceManager.GetString("LoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginLoginButton {
            get {
                return ResourceManager.GetString("LoginLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PIN Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginPinCode {
            get {
                return ResourceManager.GetString("LoginPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainAddAccount {
            get {
                return ResourceManager.GetString("MainAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenSource に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SourceCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSourceCode {
            get {
                return ResourceManager.GetString("OpenSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSourceCopying {
            get {
                return ResourceManager.GetString("OpenSourceCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying.Lesser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSourceCopyingLesser {
            get {
                return ResourceManager.GetString("OpenSourceCopyingLesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSourceLicense {
            get {
                return ResourceManager.GetString("OpenSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingAccount {
            get {
                return ResourceManager.GetString("SettingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingApplication {
            get {
                return ResourceManager.GetString("SettingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean Launch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingCleanUp {
            get {
                return ResourceManager.GetString("SettingCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if off, will be fast launch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingCleanUpSummary {
            get {
                return ResourceManager.GetString("SettingCleanUpSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingGeneral {
            get {
                return ResourceManager.GetString("SettingGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingOther {
            get {
                return ResourceManager.GetString("SettingOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingTimeline {
            get {
                return ResourceManager.GetString("SettingTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline retention number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingTimelineDownloadCount {
            get {
                return ResourceManager.GetString("SettingTimelineDownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline retention number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingTimelineOwnedNumber {
            get {
                return ResourceManager.GetString("SettingTimelineOwnedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingUseAccount {
            get {
                return ResourceManager.GetString("SettingUseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DownLoding Account Data... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashAccountDownLoading {
            get {
                return ResourceManager.GetString("SplashAccountDownLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusReplyToUser {
            get {
                return ResourceManager.GetString("StatusReplyToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusRetweetingUser {
            get {
                return ResourceManager.GetString("StatusRetweetingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabDM {
            get {
                return ResourceManager.GetString("TabDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabFavorite {
            get {
                return ResourceManager.GetString("TabFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follower に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabFollower {
            get {
                return ResourceManager.GetString("TabFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Following に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabFollowing {
            get {
                return ResourceManager.GetString("TabFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mention に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabMention {
            get {
                return ResourceManager.GetString("TabMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabTweet {
            get {
                return ResourceManager.GetString("TabTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabUser {
            get {
                return ResourceManager.GetString("TabUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} day ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeDayAgo {
            get {
                return ResourceManager.GetString("TimeDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} days ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeDaysAgo {
            get {
                return ResourceManager.GetString("TimeDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} hour ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeHourAgo {
            get {
                return ResourceManager.GetString("TimeHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} hours ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeHoursAgo {
            get {
                return ResourceManager.GetString("TimeHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} minute ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeMinuteAgo {
            get {
                return ResourceManager.GetString("TimeMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} minutes ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeMinutesAgo {
            get {
                return ResourceManager.GetString("TimeMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} second ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeSecoundAgo {
            get {
                return ResourceManager.GetString("TimeSecoundAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} seconds ago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeSecoundsAgo {
            get {
                return ResourceManager.GetString("TimeSecoundsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blocked by this user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserBlockedBy {
            get {
                return ResourceManager.GetString("UserBlockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blocking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserBlocking {
            get {
                return ResourceManager.GetString("UserBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDoBlock {
            get {
                return ResourceManager.GetString("UserDoBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDoFollow {
            get {
                return ResourceManager.GetString("UserDoFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDoMute {
            get {
                return ResourceManager.GetString("UserDoMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report spam に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDoSpam {
            get {
                return ResourceManager.GetString("UserDoSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unblock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDoUnblock {
            get {
                return ResourceManager.GetString("UserDoUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unfollow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDoUnfollow {
            get {
                return ResourceManager.GetString("UserDoUnfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unmute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDoUnmute {
            get {
                return ResourceManager.GetString("UserDoUnmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserFollow {
            get {
                return ResourceManager.GetString("UserFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Followed by this user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserFollowedBy {
            get {
                return ResourceManager.GetString("UserFollowedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Following に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserFollowing {
            get {
                return ResourceManager.GetString("UserFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Received following request に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserFollowingReceived {
            get {
                return ResourceManager.GetString("UserFollowingReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending follow reuest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserFollowingRequested {
            get {
                return ResourceManager.GetString("UserFollowingRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marked spam this user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserMarkedSpam {
            get {
                return ResourceManager.GetString("UserMarkedSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Muting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserMuting {
            get {
                return ResourceManager.GetString("UserMuting", resourceCulture);
            }
        }
    }
}
