// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Twichirp.Core.Resources {
    using System;
    using System.Reflection;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }

        public static System.Resources.ResourceManager LoadManager(string lang = "") {
            var default_name = "Twichirp.Core.Resources.StringResources";
            var asm = typeof(StringResources).GetTypeInfo().Assembly;
            var reslist = asm.GetManifestResourceNames();
            foreach (var ln in new string[] { $".{lang}", "" }.Select(x=>x.Replace("-","_"))) {
                if (reslist.Contains($"{default_name}{ln}.resources")) {
                    return new global::System.Resources.ResourceManager($"{default_name}{ln}", asm);
                }
            }
            return null;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    var ci = System.Globalization.CultureInfo.CurrentCulture;
                    System.Resources.ResourceManager temp = LoadManager(ci.Name);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppLabel {
            get {
                return ResourceManager.GetString("AppLabel", resourceCulture);
            }
        }
    }
}
